### ISSUE TITLE
KeyError: 'LowPolyInterior_Pumpkin'

### ISSUE THREAD

**Issue by yuejunpeng** [thunlp/LEGENT#12]
When I run create_traj_pumpkin, I get a bug:

Traceback (most recent call last):
  File "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/LEGENT/scripts/create_traj_pumpkin.py", line 25, in <module>
    tasks = generate_tasks()
  File "/media/ps/7890d249-37e9-43de-b60c-084f829a18df/LEGENT/scripts/create_traj_pumpkin.py", line 16, in generate_tasks
    object_id = {instance['prefab']: i for i, instance in enumerate(scene['instances'])}['LowPolyInterior_Pumpkin']
KeyError: 'LowPolyInterior_Pumpkin'

**Comment by chengzl18** [comment]
The bug has been resolved. The reason was an update in the scene generation implementation.

**Comment by yuejunpeng** [comment]
Thank you!
